//////////////////////////////////////////////////////////////////////
// This file was auto-generated by codelite's wxCrafter Plugin
// wxCrafter project file: wxcrafter.wxcp
// Do not modify this file by hand!
//////////////////////////////////////////////////////////////////////

#ifndef _CODELITE_CODELITE_WXCRAFTER_BASE_CLASSES_HPP
#define _CODELITE_CODELITE_WXCRAFTER_BASE_CLASSES_HPP

// clang-format off
#include <wx/settings.h>
#include <wx/xrc/xmlres.h>
#include <wx/xrc/xh_bmp.h>
#include <wx/frame.h>
#include <wx/iconbndl.h>
#include <wx/artprov.h>
#include <wx/sizer.h>
#include <wx/panel.h>
#include <wx/stattext.h>
#include <wx/spinctrl.h>
#include <wx/menu.h>
#if wxVERSION_NUMBER >= 2900
#include <wx/persist.h>
#include <wx/persist/toplevel.h>
#include <wx/persist/bookctrl.h>
#include <wx/persist/treebook.h>
#endif

#ifdef WXC_FROM_DIP
#undef WXC_FROM_DIP
#endif
#if wxVERSION_NUMBER >= 3100
#define WXC_FROM_DIP(x) wxWindow::FromDIP(x, NULL)
#else
#define WXC_FROM_DIP(x) x
#endif

// clang-format on

class MainFrameBaseClass : public wxFrame
{
protected:
    wxPanel* m_mainPanel;
    wxStaticText* m_staticText1;
    wxSpinCtrl* m_numberSpinCtrl;
    wxStaticText* m_binaryStaticText;
    wxPanel* m_bitPanel;
    wxBoxSizer* boxSizerBitPanel;
    wxMenuBar* m_mainMenuBar;
    wxMenu* m_name1;
    wxMenuItem* m_menuItem1;
    wxMenu* m_name2;
    wxMenuItem* m_menuItem2;

protected:
    virtual void OnSpinCtrl(wxCommandEvent& event) { event.Skip(); }
    virtual void OnExit(wxCommandEvent& event) { event.Skip(); }
    virtual void OnAbout(wxCommandEvent& event) { event.Skip(); }

public:
    wxStaticText* GetStaticText1() { return m_staticText1; }
    wxSpinCtrl* GetNumberSpinCtrl() { return m_numberSpinCtrl; }
    wxStaticText* GetBinaryStaticText() { return m_binaryStaticText; }
    wxPanel* GetBitPanel() { return m_bitPanel; }
    wxPanel* GetMainPanel() { return m_mainPanel; }
    wxMenuBar* GetMainMenuBar() { return m_mainMenuBar; }
    MainFrameBaseClass(wxWindow* parent, wxWindowID id = wxID_ANY, const wxString& title = _("Bit Converter"),
                       const wxPoint& pos = wxDefaultPosition, const wxSize& size = wxSize(500, 300),
                       long style = wxCAPTION | wxRESIZE_BORDER | wxMAXIMIZE_BOX | wxMINIMIZE_BOX | wxSYSTEM_MENU |
                                    wxCLOSE_BOX);
    virtual ~MainFrameBaseClass();
};

#endif
